import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'hr-management-system',
    name: 'HR Management System',
    description: 'Complete HR solution for Bangladeshi businesses',
    longDescription: 'A full-featured HR management system with employee tracking, payroll, leave management, and performance reviews. Built specifically for Bangladesh compliance (tax, PF, gratuity).',
    price: 5000,
    originalPrice: 8000,
    category: 'Software',
    image: '/products/hr-system.png',
    previewImages: ['/products/hr-1.png', '/products/hr-2.png', '/products/hr-3.png'],
    downloadFile: '/downloads/hr-management-v1.zip',
    features: ['Employee Database', 'Payroll Management', 'Leave Tracker', 'Performance Review', 'Bangladesh Tax Compliant'],
    rating: 4.8,
    reviews: 124,
    badge: 'Best Seller',
  },
  {
    id: '2',
    slug: 'school-management-system',
    name: 'School Management System',
    description: 'Complete school ERP for primary to higher secondary',
    longDescription: 'Manage students, teachers, classes, exams, results, and fees all in one place. Supports SSC/HSC result format and Bangladeshi academic calendar.',
    price: 7500,
    originalPrice: 12000,
    category: 'Education',
    image: '/products/school-system.png',
    previewImages: ['/products/school-1.png', '/products/school-2.png'],
    downloadFile: '/downloads/school-management-v2.zip',
    features: ['Student Management', 'Exam & Results', 'Fee Collection', 'Attendance', 'SMS Alerts'],
    rating: 4.9,
    reviews: 87,
    badge: 'New',
  },
  {
    id: '3',
    slug: 'inventory-management',
    name: 'Inventory Management System',
    description: 'Stock control for retail & wholesale business',
    longDescription: 'Real-time inventory tracking with barcode support, purchase orders, sales reports, and low-stock alerts. Works offline too.',
    price: 3500,
    originalPrice: 5000,
    category: 'Software',
    image: '/products/inventory.png',
    previewImages: ['/products/inv-1.png'],
    downloadFile: '/downloads/inventory-v1.zip',
    features: ['Barcode Scanner', 'Stock Alerts', 'Purchase Orders', 'Sales Reports', 'Multi-branch'],
    rating: 4.6,
    reviews: 56,
  },
  {
    id: '4',
    slug: 'pos-system',
    name: 'Point of Sale (POS) System',
    description: 'Fast & reliable POS for retail shops',
    longDescription: 'Touch-friendly POS system with receipt printing, discount management, daily sales summary, and customer loyalty points.',
    price: 4000,
    originalPrice: 6500,
    category: 'Software',
    image: '/products/pos.png',
    previewImages: ['/products/pos-1.png', '/products/pos-2.png'],
    downloadFile: '/downloads/pos-v3.zip',
    features: ['Touch UI', 'Receipt Printer', 'Discount System', 'Daily Reports', 'Loyalty Points'],
    rating: 4.7,
    reviews: 203,
    badge: 'Popular',
  },
  {
    id: '5',
    slug: 'accounting-software',
    name: 'Accounting Software',
    description: 'Double-entry accounting for small businesses',
    longDescription: 'Complete accounting software with VAT/tax management for Bangladesh, income/expense tracking, balance sheet, and P&L reports.',
    price: 6000,
    originalPrice: 9000,
    category: 'Finance',
    image: '/products/accounting.png',
    previewImages: ['/products/acc-1.png'],
    downloadFile: '/downloads/accounting-v2.zip',
    features: ['Double Entry', 'VAT Management', 'Bank Reconciliation', 'P&L Report', 'Balance Sheet'],
    rating: 4.5,
    reviews: 41,
  },
  {
    id: '6',
    slug: 'ecommerce-template',
    name: 'E-commerce Website Template',
    description: 'Ready-made Next.js + Tailwind shop template',
    longDescription: 'Full e-commerce template with product listing, cart, checkout, and payment integration. Includes mobile-responsive design and SEO optimization.',
    price: 2500,
    originalPrice: 4000,
    category: 'Web Template',
    image: '/products/ecommerce-template.png',
    previewImages: ['/products/ec-1.png', '/products/ec-2.png'],
    downloadFile: '/downloads/ecommerce-template-v1.zip',
    features: ['Next.js 14', 'Tailwind CSS', 'Cart System', 'SSLCommerz Ready', 'Mobile Responsive'],
    rating: 4.9,
    reviews: 312,
    badge: 'Hot',
  },
]

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug)
}

export const categories = ['All', 'Software', 'Education', 'Finance', 'Web Template']
